name: A编译candy

on:
  schedule:
     - cron: '0 3 * * *'
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 版本比较
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/lanthora/candy/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/candy/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: aarch64
          - TARGET: armv7l-eabihf
          - TARGET: armv7m-eabi
          - TARGET: arm-eabi
          - TARGET: arm-eabihf
          - TARGET: mipsel
          - TARGET: mips
          - TARGET: i686
          - TARGET: x86_64
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ matrix.TARGET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lanthora/candy
          ref: master
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - name: 编译candy
        run: |
          echo "##########################编译candy二进制#################################"
          export WORKSPACE=/opt
          export ENABLE_STRIP=1
          export TARGET=${{ env.TARGET }}
          ./scripts/build-single-file-exe.sh
          ls -alh /opt/output/$TARGET
          file /opt/output/$TARGET/candy
          mkdir -p /opt/bin
          cp -rf ./candy.cfg /opt/bin/candy.cfg
          cp -rf /opt/output/$TARGET/candy /opt/bin/candy
          cd /opt/bin
          cp -rf candy candy_upx
          upx --lzma --best candy_upx
          tar -czvf candy-linux-${{ env.TARGET }}.tar.gz candy candy_upx candy.cfg
          echo "build_time=$(TZ=UTC-8 date +%Y-%m-%d' '%H:%M:%S)" >> $GITHUB_ENV
      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: candy-${{ env.TARGET }}
          path: /opt/bin/candy-linux-${{ env.TARGET }}.tar.gz
      - name: 发布 
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间： ${{ env.build_time }}

           *.tar.gz二进制压缩包里包含：

           - candy 原版程序
           - candy_upx压缩后的程序

           二个任选一个即可 

           **[官方更新说明](https://github.com/lanthora/candy/releases)**
           
          tag_name: ${{ needs.check.outputs.ver }}
          files: /opt/bin/candy-linux-${{ env.TARGET }}.tar.gz
      - name: 删除工作流
        uses: GitRML/delete-workflow-runs@v2
        with:
         token: ${{ secrets.c8 }}
         retain_days: 2
         keep_minimum_runs: 1
